#common
equipment.common.search.searchOp=Filtro
equipment.common.search.selectAll=Tudo
equipment.common.search.serchTerm=Buscar
equipment.common.search.placeholder=Por favor, insira a palavra-chave
equipment.common.search.dateOp=Data
equipment.common.button.delete=Excluir
equipment.common.button.list=Lista
equipment.common.button.register=Registrar
equipment.common.button.modify=Modificar

#mngList.html
equipment.mngList.title=Total de Equipamentos de Câmera
equipment.mngList.descr=Gerenciar Equipamentos de Câmera
equipment.mngList.mapBtn=Mapa
equipment.mngList.listBtn=Gerenciamento de Equipamentos de Câmera
equipment.mngList.tableNumber=Nº
equipment.mngList.equipmentName=Nome do Equipamento
equipment.mngList.registrationDate=Data de Registro
equipment.mngList.equipmentType=Tipo de Equipamento
equipment.mngList.manager=Pessoa Responsável
equipment.mngList.address=Localização
equipment.mngList.RegistrationOfEnforcementEquipment=Registrar
equipment.mngList.placeholder=Por favor, insira a palavra-chave
equipment.mngList.usageStatus = Status de uso
equipment.mngList.usageStatus.useY = Em uso
equipment.mngList.usageStatus.useN = Não está em uso
equipment.mngList.search.empty = Nenhum resultado encontrado.

#log common
equipment.common.log.logId=ID Solicitado
equipment.common.log.eqpId=ID do Equipamento
equipment.common.log.creationDate=Data

#logList.html
equipment.logList.tableNumber=Nº
equipment.logList.equipmentNumber=Nº do Equipamento
equipment.logList.carNumber=Localização
equipment.logList.controlResult=Resultado do Controle
equipment.logList.requestId=ID da Solicitação

#logDetail.html
equipment.logDetail.title=Detalhes do Registro
equipment.logDetail.location=Localização

#mngRegist.html
equipment.mngRegist.title=Registrar Equipamento de Câmera
equipment.mngRegist.typesOfEnforcementEquipment=Tipo de Equipamento de Câmera
equipment.mngRegist.list=Lista
equipment.mngRegist.registrationButton=Registrar
equipment.mngRegist.manufacturer=Fabricante
equipment.mngRegist.manager=Pessoa Responsável
equipment.mngRegist.managerDept=Departamento
equipment.mngRegist.enforceementEquipmentInfo=Detalhes
equipment.mngRegist.inserImg=Imagem
equipment.mngRegist.equipmentName=Nome do Equipamento
equipment.mngRegist.modelName=Nome do Modelo
equipment.mngRegist.installationLocation=Local de Instalação
equipment.mngRegist.installationDate=Data de Instalação
equipment.mngRegist.installer=Instalador
equipment.mngRegist.installationStatus=Status da Instalação
equipment.mngRegist.installY=Instalado
equipment.mngRegist.installN=Não instalado
equipment.mngRegist.lat=Latitude
equipment.mngRegist.placeholder.lat=Por favor, insira a Latitude
equipment.mngRegist.lng=Longitude
equipment.mngRegist.placeholder.lng=Por favor, insira a Longitude
equipment.mngRegist.usageStatus = Status de uso
equipment.mngRegist.usageStatus.useY = Em uso
equipment.mngRegist.usageStatus.useN = Não está em uso
equipment.mngRegist.equipmentId = ID do equipamento

#mngRegistPlaceholcer.html
equipment.mngRegist.placeholder.equipmentName=Por favor, insira o nome do equipamento
equipment.mngRegist.placeholder.modelName=Por favor, insira o nome do modelo
equipment.mngRegist.placeholder.manufacturer=Por favor, insira o fabricante
equipment.mngRegist.placeholder.installationLocation=Por favor, insira o local de instalação
equipment.mngRegist.placeholder.installer=Por favor, insira o instalador
equipment.mngRegist.placeholder.manager=Por favor, insira a pessoa responsável
equipment.mngRegist.placeholder.managerDept=Por favor, insira o departamento
equipment.mngRegist.placeholder.enforceementEquipmentInfo=Por favor, insira os detalhes do equipamento de execução
equipment.mngRegist.placeholder.equipmentId=Por favor, insira o ID do equipamento

#EqpmngDetail.html
equipment.mngDetail.title=Informações detalhadas sobre Equipamento de Fiscalização
equipment.mngDetail.equipmentId = ID do equipamento
equipment.mngDetail.detailImg=Imagem do Equipamento
equipment.mngDetail.typesOfEquipment=Tipo de Equipamento
equipment.mngDetail.listButton=Lista
equipment.mngDetail.modifyButton=Modificar
equipment.mngDetail.manufacturer=Fabricante
equipment.mngDetail.manager=Pessoa Responsável
equipment.mngDetail.enforceementEquipmentInfo=Detalhes
equipment.mngDetail.managerDept=Departamento
equipment.mngDetail.equipmentNm=Nome do Equipamento
equipment.mngDetail.modelNm=Nome do Modelo
equipment.mngDetail.installationLocation=Local de Instalação
equipment.mngDetail.installationDate=Data de Instalação
equipment.mngDetail.installer=Instalador
equipment.mngDetail.installationStatus=Estado de Instalação
equipment.mngDetail.installY=Instalado
equipment.mngDetail.installN=Não instalado
equipment.mngDetail.management.title = Histórico de gestão
equipment.mngDetail.management.date = Data
equipment.mngDetail.management.oprtrNm = Gerente
equipment.mngDetail.management.type = Tipo
equipment.mngDetail.management.status = Status
equipment.mngDetail.management.details = Detalhes
equipment.mngDetail.management.option = Opção
equipment.mngDetail.management.none = Nenhum Resultado
equipment.mngDetail.management.modal.details = Detalhes da gestão
equipment.mngDetail.usageStatus = Status de uso
equipment.mngDetail.usageStatus.useY = Em uso
equipment.mngDetail.usageStatus.useN = Não está em uso
equipment.mngDetail.management.confirm = Tem certeza de que deseja excluir?
equipment.mngDetail.management.success = Foi processado

#EqpmngModify.html
equipment.mngModify.title=Modificar Equipamento de Câmera
equipment.mngModify.cancelButton=Cancelar
equipment.mngModify.modifyFinish=Modificar
equipment.mngModify.manufacturer=Fabricante
equipment.mngModify.manager=Pessoa Responsável
equipment.mngModify.crOprtrDept=Departamento
equipment.mngModify.eqpInfo=Info
equipment.mngModify.inserImg=Imagem
equipment.mngModify.newImg=Enviar Nova Imagem
equipment.mngModify.typesOfEnforcementEquipment=Tipo de Equipamento de Câmera
equipment.mngModify.equipmentName=Nome do Equipamento
equipment.mngModify.modelNm=Nome do Modelo
equipment.mngModify.installationLocation=Local de Instalação
equipment.mngModify.installationDate=Data de Instalação
equipment.mngModify.installationStatus=Estado de Instalação
equipment.mngModify.installY=Instalado
equipment.mngModify.installN=Não instalado
equipment.mngModify.usageStatus = Status de uso
equipment.mngModify.usageStatus.useY = Em uso
equipment.mngModify.usageStatus.useN = Não está em uso
equipment.mngModify.equipmentId = ID do equipamento

#FacilityMngList.html
equipment.facilityMngList.title=Total de Instalações de Tráfego
equipment.facilityMngList.descr=Gerenciar instalações de tráfego
equipment.facilityMngList.mapBtn=Mapa
equipment.facilityMngList.listBtn=Gerenciamento de Instalações de Tráfego
equipment.facilityMngList.tableNumber=Nº
equipment.facilityMngList.facType=Tipo
equipment.facilityMngList.facId=ID da Instalação
equipment.facilityMngList.facName=Nome
equipment.facilityMngList.facStts=Status
equipment.facilityMngList.facLocation=Localização
equipment.facilityMngList.facDate=Data de Instalação
equipment.facilityMngList.facInCharge=Pessoa Responsável
equipment.facilityMngList.register=Registrar
equipment.facilityMngList.search.empty = Nenhum resultado encontrado.

#FacilityMngRegist.html
equipment.facilityRegist.title=Cadastrar Instalação de Tráfego
equipment.facilityRegist.trafficFacilityName=Nome da Instalação de Tráfego
equipment.facilityRegist.trafficFacilityType=Tipo de Instalação de Tráfego
equipment.facilityRegist.trafficFacilityDivision=Divisão da Instalação de Tráfego
equipment.facilityRegist.trafficFacilityCategory=Categoria da Instalação de Tráfego
equipment.facilityRegist.trafficFacilityStatus=Status da Instalação de Tráfego
equipment.facilityRegist.useYn=Status de Uso
equipment.facilityRegist.useY=Em uso
equipment.facilityRegist.useN=Não está em uso
equipment.facilityRegist.area=Área
equipment.facilityRegist.lat=Latitude
equipment.facilityRegist.lng=Longitude
equipment.facilityRegist.installationLocation=Local da Instalação
equipment.facilityRegist.image=Imagem
equipment.facilityRegist.details=Detalhes
equipment.facilityRegist.manager=Pessoa Responsável
equipment.facilityRegist.managerDept=Departamento
equipment.facilityRegist.placeholder.trafficFacilityName=Por favor, insira o nome da instalação de tráfego
equipment.facilityRegist.placeholder.trafficFacilityStatus=Por favor, insira o status da instalação de tráfego
equipment.facilityRegist.placeholder.lat=Por favor, insira a latitude
equipment.facilityRegist.placeholder.lng=Por favor, insira a longitude
equipment.facilityRegist.placeholder.installationLocation=Por favor, insira o local da instalação
equipment.facilityRegist.placeholder.enforceementEquipmentInfo=Por favor, insira os detalhes
equipment.facilityRegist.placeholder.manager=Por favor, insira a pessoa responsável
equipment.facilityRegist.placeholder.managerDept=Por favor, insira o departamento

#FacilityMngDetail.html
equipment.facilityDetail.title=Informações detalhadas sobre Instalação de Tráfego
equipment.facilityDetail.trafficFacilityName=Nome da Instalação de Tráfego
equipment.facilityDetail.trafficFacilityType=Tipo de Instalação de Tráfego
equipment.facilityDetail.trafficFacilityDivision=Divisão da Instalação de Tráfego
equipment.facilityDetail.trafficFacilityCategory=Categoria da Instalação de Tráfego
equipment.facilityDetail.trafficFacilityStatus=Status da Instalação de Tráfego
equipment.facilityDetail.regDate=Data de Registro
equipment.facilityDetail.installationLocation=Local de Instalação
equipment.facilityDetail.personInCharge=Pessoa Responsável
equipment.facilityDetail.department=Departamento
equipment.facilityDetail.image=Imagem
equipment.facilityDetail.details=Detalhes
equipment.facilityDetail.useYn=Status de Uso
equipment.facilityDetail.useY=Em uso
equipment.facilityDetail.useN=Não está em uso
equipment.facilityDetail.area=Área
equipment.facilityDetail.fileEmpty=Nenhum arquivo enviado.
equipment.facilityDetail.management.title = Histórico de gestão
equipment.facilityDetail.management.oprtrNm = Gerente
equipment.facilityDetail.management.mntnType = Tipo
equipment.facilityDetail.management.mntnStts = Status
equipment.facilityDetail.management.date = Data
equipment.facilityDetail.management.desc = Detalhes
equipment.facilityDetail.management.option = Opção
equipment.facilityDetail.management.none = Nenhum histórico de gestão
equipment.facilityDetail.management.modal.details = Detalhes da gestão

#FacilityMngModify.html
equipment.facilityModify.title=Modificar Instalação de Tráfego
equipment.facilityModify.trafficFacilityName=Nome da Instalação de Tráfego
equipment.facilityModify.trafficFacilityType=Tipo de Instalação de Tráfego
equipment.facilityModify.trafficFacilityDivision=Divisão da Instalação de Tráfego
equipment.facilityModify.trafficFacilityCategory=Categoria da Instalação de Tráfego
equipment.facilityModify.trafficFacilityStatus=Status
equipment.facilityModify.location=Localização
equipment.facilityModify.personInCharge=Pessoa Responsável
equipment.facilityModify.department=Departamento
equipment.facilityModify.image=Imagem
equipment.facilityModify.lat=Latitude
equipment.facilityModify.lng=Longitude
equipment.facilityModify.details=Detalhes
equipment.facilityModify.useYn=Status de Uso
equipment.facilityModify.useY=Usar
equipment.facilityModify.useN=Não Usar
equipment.facilityModify.area=Área
equipment.facilityModify.placeholder.trafficFacilityName=Por favor, insira o nome da instalação de tráfego
equipment.facilityModify.placeholder.trafficFacilityStatus=Por favor, insira o status da instalação de tráfego
equipment.facilityModify.placeholder.lat=Por favor, insira a latitude
equipment.facilityModify.placeholder.lng=Por favor, insira a longitude
equipment.facilityModify.placeholder.installationLocation=Por favor, insira o local da instalação

#orgnzMngList.html
organization.orgnzMngList.title = Total de Organizações / Regiões
organization.orgnzMngList.title.desc = Gerenciar Organizações & Regiões
organization.orgnzMngList.button.map = Mapa
organization.orgnzMngList.button.list = Organizações & Regiões Relacionadas
organization.orgnzMngList.map.title = Lista de Organizações/Regiões
organization.orgnzMngList.map.placeholder = Por favor, insira a palavra-chave
organization.orgnzMngList.map.table.name = Nome
organization.orgnzMngList.map.table.location = Localização
organization.orgnzMngList.list.btn.register = Registrar
organization.orgnzMngList.list.table.number = N.º
organization.orgnzMngList.list.table.name = Nome
organization.orgnzMngList.list.table.location = Localização
organization.orgnzMngList.list.table.status = Status
organization.orgnzMngList.list.table.registrant = Registrante
organization.orgnzMngList.list.table.registerDate = Data de Registro

#orgnzMngDetail.html
organization.orgnzMngDetail.title = Detalhes das Organizações / Regiões
organization.orgnzMngDetail.name = Nome
organization.orgnzMngDetail.registerDate = Data de Registro
organization.orgnzMngDetail.usageStatus = Status de Uso
organization.orgnzMngDetail.usageStatus.useY = Em uso
organization.orgnzMngDetail.usageStatus.useN = Não está em uso
organization.orgnzMngDetail.status = Status
organization.orgnzMngDetail.location = Localização
organization.orgnzMngDetail.details = Detalhes
organization.orgnzMngDetail.images = Imagens

#orgnzMngModify.html
organization.orgnzMngModify.title = Modificar Organizações / Regiões Relacionadas
organization.orgnzMngModify.name = Nome
organization.orgnzMngModify.usageStatus = Status de Uso
organization.orgnzMngModify.usageStatus.useY = Em uso
organization.orgnzMngModify.usageStatus.useN = Não está em uso
organization.orgnzMngModify.status = Status
organization.orgnzMngModify.location = Localização
organization.orgnzMngModify.details = Detalhes
organization.orgnzMngModify.images = Imagens
organization.orgnzMngModify.lat = Latitude
organization.orgnzMngModify.lng = Longitude
organization.orgnzMngModify.btn.cancel = Cancelar
organization.orgnzMngModify.btn.delete = Excluir
organization.orgnzMngModify.btn.modify = Modificar
organization.orgnzMngModify.placeholder.name = Por favor, insira o Nome
organization.orgnzMngModify.placeholder.location = Por favor, insira a Localização
organization.orgnzMngModify.placeholder.lat = Por favor, insira a Latitude
organization.orgnzMngModify.placeholder.lng = Por favor, insira a Longitude
organization.orgnzMngModify.placeholder.status = Por favor, insira o Status
organization.orgnzMngModify.placeholder.details = Por favor, insira os Detalhes

#orgnzMngRegist.html
organization.orgnzMngRegist.title = Registrar Organizações / Regiões Relacionadas
organization.orgnzMngRegist.name = Nome
organization.orgnzMngRegist.useYn = Status de Uso
organization.orgnzMngRegist.useY = Em uso
organization.orgnzMngRegist.useN = Não está em uso
organization.orgnzMngRegist.location = Localização
organization.orgnzMngRegist.lat = Latitude
organization.orgnzMngRegist.lng = Longitude
organization.orgnzMngRegist.image = Imagem
organization.orgnzMngRegist.status = Status
organization.orgnzMngRegist.details = Detalhes
organization.orgnzMngRegist.btn.File = Carregar Arquivo
organization.orgnzMngRegist.btn.list = Lista
organization.orgnzMngRegist.btn.register = Registrar
organization.orgnzMngRegist.placeholder.name = Por favor, insira o Nome
organization.orgnzMngRegist.placeholder.location = Por favor, insira a Localização
organization.orgnzMngRegist.placeholder.lat = Por favor, insira a Latitude
organization.orgnzMngRegist.placeholder.lng = Por favor, insira a Longitude
organization.orgnzMngRegist.placeholder.status = Por favor, insira o Status
organization.orgnzMngRegist.placeholder.details = Por favor, insira os Detalhes
