#common
equipment.common.search.searchOp=Filter
equipment.common.search.selectAll=All
equipment.common.search.serchTerm=Search
equipment.common.search.placeholder=Please enter keyword
equipment.common.search.dateOp=Date
equipment.common.button.delete=Delete
equipment.common.button.list=List
equipment.common.button.register=Register
equipment.common.button.modify=Modify

#mngList.html
equipment.mngList.title=Total Enforcement Camera
equipment.mngList.descr=Manage Enforcement Camera
equipment.mngList.mapBtn=Map
equipment.mngList.listBtn=Enforcement Equipment Management
equipment.mngList.tableNumber=No.
equipment.mngList.equipmentName=Equipment Name
equipment.mngList.registrationDate=Registered Date
equipment.mngList.equipmentType=Equipment Type
equipment.mngList.manager=Person in Charge
equipment.mngList.address=Location
equipment.mngList.RegistrationOfEnforcementEquipment=Register
equipment.mngList.placeholder= Please enter keyword
equipment.mngList.usageStatus = Usage status
equipment.mngList.usageStatus.useY = In use
equipment.mngList.usageStatus.useN = Not in use
equipment.mngList.search.empty = No Results Found.

#log common
equipment.common.log.logId=Requested ID
equipment.common.log.eqpId=Equipment Id
equipment.common.log.creationDate=Date

#logList.html
equipment.logList.tableNumber=No.
equipment.logList.equipmentNumber=Equipment No.
equipment.logList.carNumber=Location
equipment.logList.controlResult=Control Result
equipment.logList.requestId=Request ID

#logDetail.html
equipment.logDetail.title=Log Details
equipment.logDetail.location=Location

#mngRegist.html
equipment.mngRegist.title=Register Enforcement Equipment
equipment.mngRegist.typesOfEnforcementEquipment=Enforcement Equipment Type
equipment.mngRegist.list=List
equipment.mngRegist.registrationButton=Register
equipment.mngRegist.manufacturer=Manufacturer
equipment.mngRegist.manager=Person in Charge
equipment.mngRegist.managerDept=Department
equipment.mngRegist.enforceementEquipmentInfo=Details
equipment.mngRegist.inserImg=Image
equipment.mngRegist.equipmentName=Equipment Name
equipment.mngRegist.modelName=Model Name
equipment.mngRegist.installationLocation=Installation location
equipment.mngRegist.installationDate=Installation Date
equipment.mngRegist.installer=Installer
equipment.mngRegist.installationStatus=Installation Status
equipment.mngRegist.installY=Installed
equipment.mngRegist.installN=Not installed
equipment.mngRegist.lat=Latitude
equipment.mngRegist.placeholder.lat=Please Enter Latitude
equipment.mngRegist.lng=Longitude
equipment.mngRegist.placeholder.lng=Please Enter Longitude
equipment.mngRegist.usageStatus = Usage status
equipment.mngRegist.usageStatus.useY = In use
equipment.mngRegist.usageStatus.useN = Not in use
equipment.mngRegist.equipmentId = Equipment ID

#mngRegistPlaceholcer.html
equipment.mngRegist.placeholder.equipmentName=Please Enter Equipment Name
equipment.mngRegist.placeholder.modelName=Please Enter Model Name
equipment.mngRegist.placeholder.manufacturer=Please Enter Manufacturer
equipment.mngRegist.placeholder.installationLocation=Please Enter Location
equipment.mngRegist.placeholder.installer=Please Enter installer
equipment.mngRegist.placeholder.manager=Please Enter Person in Charge
equipment.mngRegist.placeholder.managerDept=Please Enter Department
equipment.mngRegist.placeholder.enforceementEquipmentInfo=Please Enter Details
equipment.mngRegist.placeholder.equipmentId=Please Enter Equipment ID

#EqpmngDetail.html
equipment.mngDetail.title=Enforcement Equipment Detailed Information
equipment.mngDetail.equipmentId = Equipment ID
equipment.mngDetail.detailImg=Equipment Image
equipment.mngDetail.typesOfEquipment=Equipment Type
equipment.mngDetail.listButton=List
equipment.mngDetail.modifyButton=Modify
equipment.mngDetail.manufacturer=Manufacturer
equipment.mngDetail.manager=Person in Charge
equipment.mngDetail.enforceementEquipmentInfo=Details
equipment.mngDetail.managerDept=Department
equipment.mngDetail.equipmentNm=Equipment Name
equipment.mngDetail.modelNm=Model Name
equipment.mngDetail.installationLocation=Installation location
equipment.mngDetail.installationDate=Installation Date
equipment.mngDetail.installer=Installer
equipment.mngDetail.installationStatus=Installation Status
equipment.mngDetail.installY=Installed
equipment.mngDetail.installN=Not installed
equipment.mngDetail.management.title=Management history
equipment.mngDetail.management.date=Date
equipment.mngDetail.management.oprtrNm=Manager
equipment.mngDetail.management.type=Type
equipment.mngDetail.management.status=Status
equipment.mngDetail.management.details=Details
equipment.mngDetail.management.option=Option
equipment.mngDetail.management.none=None Result
equipment.mngDetail.management.modal.details = Management details
equipment.mngDetail.usageStatus = Usage status
equipment.mngDetail.usageStatus.useY = In use
equipment.mngDetail.usageStatus.useN = Not in use
equipment.mngDetail.management.confirm = Are you sure you want to delete?
equipment.mngDetail.management.success = It has been processed

#EqpmngModify.html
equipment.mngModify.title=Modify Enforcement Equipment
equipment.mngModify.cancelButton=Cancel
equipment.mngModify.modifyFinish=Modify
equipment.mngModify.manufacturer=Manufacturer
equipment.mngModify.manager=Person in Charge
equipment.mngModify.crOprtrDept=Department
equipment.mngModify.eqpInfo=Info
equipment.mngModify.inserImg=Image
equipment.mngModify.newImg=Upload New Image
equipment.mngModify.typesOfEnforcementEquipment=Enforcement Equipment Type
equipment.mngModify.equipmentName=Equipment Name
equipment.mngModify.modelNm=Model Name
equipment.mngModify.installationLocation=Installation location
equipment.mngModify.installationDate=Installation Date
equipment.mngModify.installationStatus=Installation Status
equipment.mngModify.installY=Installed
equipment.mngModify.installN=Not installed
equipment.mngModify.usageStatus = Usage status
equipment.mngModify.usageStatus.useY = In use
equipment.mngModify.usageStatus.useN = Not in use
equipment.mngModify.equipmentId = Equipment ID

#FacilityMngList.html
equipment.facilityMngList.title=Total Traffic Facility
equipment.facilityMngList.descr=Manage traffic facilities
equipment.facilityMngList.mapBtn=Map
equipment.facilityMngList.listBtn=Traffic Facility Management
equipment.facilityMngList.tableNumber=No.
equipment.facilityMngList.facType=Type
equipment.facilityMngList.facId=Facility ID
equipment.facilityMngList.facName=Name
equipment.facilityMngList.facStts=Status
equipment.facilityMngList.facLocation=Location
equipment.facilityMngList.facDate=Installed Date
equipment.facilityMngList.facInCharge=Person in Charge
equipment.facilityMngList.register=Register
equipment.facilityMngList.search.empty = No Results Found.

#FacilityMngRegist.html
equipment.facilityRegist.title=Register Traffic Facility
equipment.facilityRegist.trafficFacilityName=Traffic Facility Name
equipment.facilityRegist.trafficFacilityType=Traffic Facility Type
equipment.facilityRegist.trafficFacilityDivision=Traffic Facility Division
equipment.facilityRegist.trafficFacilityCategory=Traffic Facility Category
equipment.facilityRegist.trafficFacilityStatus=Traffic Facility Status
equipment.facilityRegist.useYn=Use Status
equipment.facilityRegist.useY=In use
equipment.facilityRegist.useN=Not in use
equipment.facilityRegist.area=Area
equipment.facilityRegist.lat=Latitude
equipment.facilityRegist.lng=Longitude
equipment.facilityRegist.installationLocation=Installation Location
equipment.facilityRegist.image=Image
equipment.facilityRegist.details=Details
equipment.facilityRegist.manager=Person in Charge
equipment.facilityRegist.managerDept=Department
equipment.facilityRegist.placeholder.trafficFacilityName=Please Enter Traffic Facility Name
equipment.facilityRegist.placeholder.trafficFacilityStatus=Please Enter Traffic Facility Status
equipment.facilityRegist.placeholder.lat=Please Enter Latitude
equipment.facilityRegist.placeholder.lng=Please Enter Longitude
equipment.facilityRegist.placeholder.installationLocation=Please Enter Location
equipment.facilityRegist.placeholder.enforceementEquipmentInfo=Please Enter Details
equipment.facilityRegist.placeholder.manager=Please Enter Person in Charge
equipment.facilityRegist.placeholder.managerDept=Please Enter Department

#FacilityMngDetail.html
equipment.facilityDetail.title=Traffic Facility Detailed Information
equipment.facilityDetail.trafficFacilityName=Traffic Facility Name
equipment.facilityDetail.trafficFacilityType=Traffic Facility Type
equipment.facilityDetail.trafficFacilityDivision=Traffic Facility Division
equipment.facilityDetail.trafficFacilityCategory=Traffic Facility Category
equipment.facilityDetail.trafficFacilityStatus=Traffic Facility Status
equipment.facilityDetail.regDate=Registration date
equipment.facilityDetail.installationLocation=Installation Location
equipment.facilityDetail.personInCharge=Person in Charge
equipment.facilityDetail.department=Department
equipment.facilityDetail.image=Image
equipment.facilityDetail.details=Details
equipment.facilityDetail.useYn=Use Status
equipment.facilityDetail.useY=In Use
equipment.facilityDetail.useN=Not in use
equipment.facilityDetail.area=Area
equipment.facilityDetail.fileEmpty=There are no files uploaded.
equipment.facilityDetail.management.title=Management history
equipment.facilityDetail.management.oprtrNm=Manager
equipment.facilityDetail.management.mntnType=Type
equipment.facilityDetail.management.mntnStts=Status
equipment.facilityDetail.management.date=Date
equipment.facilityDetail.management.desc=Details
equipment.facilityDetail.management.option=Option
equipment.facilityDetail.management.none=No management history
equipment.facilityDetail.management.modal.details=Management Details

#FacilityMngModify.html
equipment.facilityModify.title=Modify Traffic Facility
equipment.facilityModify.trafficFacilityName=Traffic Facility Name
equipment.facilityModify.trafficFacilityType=Traffic Facility Type
equipment.facilityModify.trafficFacilityDivision=Traffic Facility Division
equipment.facilityModify.trafficFacilityCategory=Traffic Facility Category
equipment.facilityModify.trafficFacilityStatus=Status
equipment.facilityModify.location=Location
equipment.facilityModify.personInCharge=Person in Charge
equipment.facilityModify.department=Department
equipment.facilityModify.image=Image
equipment.facilityModify.lat=Latitude
equipment.facilityModify.lng=Longitude
equipment.facilityModify.details=Details
equipment.facilityModify.useYn=Use Status
equipment.facilityModify.useY=Use
equipment.facilityModify.useN=Not Use
equipment.facilityModify.area=Area
equipment.facilityModify.placeholder.trafficFacilityName=Please Enter Traffic Facility Name
equipment.facilityModify.placeholder.trafficFacilityStatus=Please Enter Traffic Facility Status
equipment.facilityModify.placeholder.lat=Please Enter Latitude
equipment.facilityModify.placeholder.lng=Please Enter Longitude
equipment.facilityModify.placeholder.installationLocation=Please Enter Location

#orgnzMngList.html
organization.orgnzMngList.title = Total Organizations / Regions
organization.orgnzMngList.title.desc = Manage Organizations & Regions
organization.orgnzMngList.button.map = Map
organization.orgnzMngList.button.list = Related Organizations & Regions
organization.orgnzMngList.map.title = Organizations/Regions List
organization.orgnzMngList.map.placeholder = Please enter keyword
organization.orgnzMngList.map.table.name = Name
organization.orgnzMngList.map.table.location = Location
organization.orgnzMngList.list.btn.register = Register
organization.orgnzMngList.list.table.number = No.
organization.orgnzMngList.list.table.name = Name
organization.orgnzMngList.list.table.location = Location
organization.orgnzMngList.list.table.status = Status
organization.orgnzMngList.list.table.registrant = Registrant
organization.orgnzMngList.list.table.registerDate = Registration date

#orgnzMngDetail.html
organization.orgnzMngDetail.title = Organizations / Regions details
organization.orgnzMngDetail.name = Name
organization.orgnzMngDetail.registerDate = Registration date
organization.orgnzMngDetail.usageStatus = Usage status
organization.orgnzMngDetail.usageStatus.useY = In use
organization.orgnzMngDetail.usageStatus.useN = Not in use
organization.orgnzMngDetail.status = Status
organization.orgnzMngDetail.location = Location
organization.orgnzMngDetail.details = Details
organization.orgnzMngDetail.images = Images

#orgnzMngModify.html
organization.orgnzMngModify.title = Modify Related Organizaions / Regions
organization.orgnzMngModify.name = Name
organization.orgnzMngModify.usageStatus = Usage status
organization.orgnzMngModify.usageStatus.useY = In use
organization.orgnzMngModify.usageStatus.useN = Not in use
organization.orgnzMngModify.status = Status
organization.orgnzMngModify.location = Location
organization.orgnzMngModify.details = Details
organization.orgnzMngModify.images = Images
organization.orgnzMngModify.lat = Latitude
organization.orgnzMngModify.lng = Longitude
organization.orgnzMngModify.btn.cancel = Cancel
organization.orgnzMngModify.btn.delete = Delete
organization.orgnzMngModify.btn.modify = Modify
organization.orgnzMngModify.placeholder.name = Please enter Name
organization.orgnzMngModify.placeholder.location = Please enter Location
organization.orgnzMngModify.placeholder.lat = Please enter Latitude
organization.orgnzMngModify.placeholder.lng = Please enter Longitude
organization.orgnzMngModify.placeholder.status = Please enter Status
organization.orgnzMngModify.placeholder.details = Please enter Details

#orgnzMngRegist.html
organization.orgnzMngRegist.title = Register Related Organizaions / Regions
organization.orgnzMngRegist.name = Name
organization.orgnzMngRegist.useYn = Use Status
organization.orgnzMngRegist.useY=Use
organization.orgnzMngRegist.useN=Not Use
organization.orgnzMngRegist.location = Location
organization.orgnzMngRegist.lat=Latitude
organization.orgnzMngRegist.lng=Longitude
organization.orgnzMngRegist.image=Image
organization.orgnzMngRegist.status=Status
organization.orgnzMngRegist.details=Details
organization.orgnzMngRegist.btn.File=File Upload
organization.orgnzMngRegist.btn.list=List
organization.orgnzMngRegist.btn.register=Register
organization.orgnzMngRegist.placeholder.name=Please enter name
organization.orgnzMngRegist.placeholder.location=Please enter Location
organization.orgnzMngRegist.placeholder.lat=Please enter Latitude
organization.orgnzMngRegist.placeholder.lng=Please enter Longitude
organization.orgnzMngRegist.placeholder.status=Please enter Status
organization.orgnzMngRegist.placeholder.details=Please enter Details
