#login.html
enforcement.admin.login=Login

#dashboardmain.html
enforcement.admin.dashBoardMain=Main Dashboard

#common
enforcement.common.search.searchOp=Type
enforcement.common.search.selectAll=All
enforcement.common.search.serchTerm=Search
enforcement.common.search.placeholder=Please enter keyword
enforcement.common.search.dateOp=Date
enforcement.common.search.reset=Reset Search
enforcement.common.search.registBtn=Regist
enforcement.common.search.searchType.requestedId=Requested Id
enforcement.common.search.searchType.requestedBy=Requested by
enforcement.common.button.delete=Delete
enforcement.common.button.list=List
enforcement.common.button.register=Register
enforcement.common.button.modify=Modify
enforcement.common.button.tfcEnfRegist=New traffic enforcement registration

#searchdriver.html
enforcement.driver.search.title=Driver Search
enforcement.driver.search.descr=You can search by driver's license number.
enforcement.driver.search.searchOp=Filter 
enforcement.driver.search.tableNo=No.
enforcement.driver.search.placeholder=Please enter keyword
enforcement.driver.search.name=Name
enforcement.driver.search.phNum=Contact
enforcement.driver.search.searchAddress=Address
enforcement.driver.search.licenseCheck=License Status
enforcement.driver.search.lcnCkAvailable=Valid
enforcement.driver.search.lcnCkStop=Suspended
enforcement.driver.search.lcnCkCancellation=Invalid
enforcement.driver.search.docType=Document Type
enforcement.driver.search.docNo=Document Number
enforcement.driver.search.nid=NID
enforcement.driver.search.searchTitle=Driver Information
enforcement.driver.search.vehicleNo=Vehicle No
enforcement.driver.search.vehicleType=Vehicle Type
enforcement.driver.search.check=Search
enforcement.driver.search.reset=Reset Search
enforcement.driver.search.content=No Search Result
enforcement.driver.search.closeButton=Close
enforcement.driver.search.address=Address
enforcement.driver.search.email=E-Mail
enforcement.driver.search.driverLicense=License No.
enforcement.driver.search.driverType=License Type.
enforcement.driver.search.classes=Classes
enforcement.driver.search.expiration=License Expiration Date.
enforcement.driver.search.sex=Sex
enforcement.driver.search.birth=Birthday

#SearchDriverDetail.html
enforcement.driver.search.Detail.title=Driver Information
enforcement.driver.search.Detail.subtitle=Driver Detailed Information
enforcement.driver.search.Detail.name=Name
enforcement.driver.search.Detail.email=Email Address
enforcement.driver.search.Detail.nid=NID
enforcement.driver.search.Detail.docType=Document Type
enforcement.driver.search.Detail.docNo=Document Number
enforcement.driver.search.Detail.sex=Sex
enforcement.driver.search.Detail.driverLicense=License No.
enforcement.driver.search.Detail.LicenseCheck=License Status
enforcement.driver.search.Detail.expiration=License Expiration Date
enforcement.driver.search.Detail.drivetLicenseDate=Issued Date
enforcement.driver.search.Detail.driverRestrictions=Driver restrictions
enforcement.driver.search.Detail.vehicleRestrictions=Vehicle restrictions
enforcement.driver.search.Detail.licenseRenewal=Renewal Count
enforcement.driver.search.Detail.phoneNum=Contact
enforcement.driver.search.Detail.nationality=Nationality
enforcement.driver.search.Detail.address=Address
enforcement.driver.search.Detail.driverType=License Type.
enforcement.driver.search.Detail.birth=BirthDay
enforcement.driver.search.Detail.vehicleNo=Vehicle No
enforcement.driver.search.Detail.vehicleType=Vehicle Type
enforcement.driver.search.Detail.tfcEnfId=Enforcement Id
enforcement.driver.search.Detail.vioNm=Violator Name
enforcement.driver.search.Detail.roadAddr=Enforcement Road Address
enforcement.driver.search.Detail.dvrLcenId=Violator DriverLicenseId
enforcement.driver.search.Detail.tfcEnfDt=Enforcement Date
enforcement.driver.search.Detail.found=Found
enforcement.driver.search.Detail.result=results
enforcement.driver.search.Detail.resultNone=Not Found TrafficEnforcement Info 
enforcement.driver.search.Detail.enforcementHist=Traffic enforcement history 
enforcement.driver.search.Detail.enforcementHist.desc= This is a list of previous traffic enforcement records.

#searchCar.html
enforcement.car.search.title=Vehicle Search
enforcement.car.search.descr=You can search by vehicle plate number.
enforcement.car.search.carNum=Vehicle No.
enforcement.car.search.searchOp=Filter
enforcement.car.search.carInfo=Vehicle Information
enforcement.car.search.NID=Owner NID or Company
enforcement.car.search.vehicleNo=Vehicle No
enforcement.car.search.vehicleType=Vehicle Type
enforcement.car.search.check=Search
enforcement.car.search.reset=Reset Search
enforcement.car.search.content=No Search Result
enforcement.car.search.closeButton=Close
enforcement.car.search.address=Address
enforcement.car.search.email=E-Mail
enforcement.car.search.docType=Document Type
enforcement.car.search.docNo=Document Number
enforcement.car.search.state=State
enforcement.car.search.area=Area
enforcement.car.search.driverLicense=License No.
enforcement.car.search.driverType=License Type.
enforcement.car.search.expiration=License Expiration Date.
enforcement.car.search.name=Name
enforcement.car.search.phNum=Contact
enforcement.car.search.searchAddress=Address
enforcement.car.search.birth=Birthday
enforcement.car.search.resultNone=There are no vehicle search results

#SearchCarDetail.html
enforcement.car.search.Detail.title=Vehicle Information
enforcement.car.search.Detail.title.history=Traffic enforcement history
enforcement.car.search.Detail.subtitle=Driver Detailed Information
enforcement.car.search.Detail.name=Name
enforcement.car.search.Detail.email=Email Address
enforcement.car.search.Detail.nid=NID
enforcement.car.search.Detail.driverLicense=License No.
enforcement.car.search.Detail.LicenseCheck=License Status
enforcement.car.search.Detail.expiration=License Expiration Date
enforcement.car.search.Detail.drivetLicenseDate=Issued Date
enforcement.car.search.Detail.licenseRenewal=Renewal Count
enforcement.car.search.Detail.phoneNum=Contact
enforcement.car.search.Detail.nationality=Nationality
enforcement.car.search.Detail.address=Address
enforcement.car.search.Detail.docType=Document Type
enforcement.car.search.Detail.docNo=Document Number
enforcement.car.search.Detail.state=State
enforcement.car.search.Detail.area=Area
enforcement.car.search.Detail.driverType=License Type.
enforcement.car.search.Detail.birth=BirthDay
enforcement.car.search.Detail.vehicleNo=Vehicle No
enforcement.car.search.Detail.vehicleType=Vehicle Type
enforcement.car.search.Detail.tfcEnfId=Enforcement Id
enforcement.car.search.Detail.vioNm=Violator Name
enforcement.car.search.Detail.roadAddr=Enforcement Road Address
enforcement.car.search.Detail.dvrLcenId=Violator DriverLicenseId
enforcement.car.search.Detail.tfcEnfDt=Enforcement Date
enforcement.car.search.Detail.found=Found
enforcement.car.search.Detail.result=results
enforcement.car.search.Detail.enforcementHist=Traffic enforcement history
enforcement.car.search.Detail.fine = Amount of fine
enforcement.car.search.Detail.result.empty = No search results found.
enforcement.car.search.Detail.enforceCode = Code
enforcement.car.search.Detail.enforceCode.0 = Speeding
enforcement.car.search.Detail.enforceCode.1 = Bus
enforcement.car.search.Detail.enforceCode.2 = Signal violation
enforcement.car.search.Detail.speedLimit = Speed limit
enforcement.car.search.Detail.enfSpeed = Violation speed
enforcement.car.search.Detail.loading = Loading...
enforcement.car.search.Detail.table.number = No.
enforcement.car.search.Detail.table.payment.title = Payment Status
enforcement.car.search.Detail.table.payment.y = Paid
enforcement.car.search.Detail.table.payment.n = Unpaid

#infoList.html
enforcement.info.list.title=Total Traffic Enforcement
enforcement.info.list.descr=Inquiry via violation, enforcement no., vehicle no., name, or period
enforcement.info.list.check=Search
enforcement.info.list.tableNumber=No.
enforcement.info.list.enforcementNumber=Enforcement No.
enforcement.info.list.enforcementType=Enforcement Type
enforcement.info.list.enforcementDate=Date
enforcement.info.list.enforcementPlace=Location
enforcement.info.list.violationName=Violation
enforcement.info.list.violatorName=Name
enforcement.info.list.vhRegNo=Vehicle No.
enforcement.info.list.infoRegistration=Register
enforcement.info.list.selectAll=All
enforcement.info.list.paid=Paid
enforcement.info.list.nonPaid=Unpaid
enforcement.info.list.payStatus=Payment Status

#infoDetail.html
enforcement.infoDetail.title=Traffic Enforcement Details
enforcement.infoDetail.enforcementNumber=Enforcement No.
enforcement.infoDetail.descr=Traffic Enforcement Detailed Information
enforcement.infoDetail.violationNumber=Violation No.
enforcement.infoDetail.placeOfViolate=Location
enforcement.infoDetail.docType=Document Type
enforcement.infoDetail.docNo=Document No
enforcement.infoDetail.intermittentName=Violation
enforcement.infoDetail.fine=Penalty
enforcement.infoDetail.violationDate=Date
enforcement.infoDetail.violatorsName=Name
enforcement.infoDetail.relatedAccidentInformation=Related Accident Info
enforcement.infoDetail.paymentStatus=Penalty Payment Status
enforcement.infoDetail.list=List
enforcement.infoDetail.modifyButton=Modify
enforcement.infoDetail.tfcEnfDetail=Details
enforcement.infoDetail.tfcEnfInfoImage=Attachment
enforcement.infoDetail.lng=Longitude
enforcement.infoDetail.lat=Latitude
enforcement.infoDetail.vehicle=Vehicle
enforcement.infoDetail.licenseTy=License Type
enforcement.infoDetail.birthday=Birthday
enforcement.infoDetail.phone=Phone
enforcement.infoDetail.email=Email
enforcement.infoDetail.enfInfo=Enforcement Title
enforcement.infoDetail.vehiclRegNo=Vehicle No.
enforcement.infoDetail.vehiclType=Vehicle Type
enforcement.infoDetail.vehiclNo=Vehicle Plate No.
enforcement.infoDetail.courtName=Court
enforcement.infoDetail.law=Illegal Law
enforcement.infoDetail.lawChoose=Illegal Law Choose
enforcement.infoDetail.lawDetail=Illegal Law Detail
enforcement.infoDetail.detaileType=Type
enforcement.infoDetail.polInCharge=Officer
enforcement.infoDetail.jur.msg=It will be entered automatically
enforcement.infoDetail.deleteMessage=Do you want to delete traffic enforcement information?
enforcement.infoDetail.placePayment=Place payment
enforcement.infoDetail.div.province = Province
enforcement.infoDetail.div.district = District
enforcement.infoDetail.lmtSpd=Limit Speed
enforcement.infoDetail.vioSpd=Violation Speed
enforcement.infoDetail.ovrSpd=Excess Speed
enforcement.infoDetail.lane=Lane
enforcement.infoDetail.number.find= Please click the search button in the top right corner of the table to enter the number.

#infoRegist.html
enforcement.infoRegist.placeholder.title=Please Enter Enforcement Title
enforcement.infoRegist.placeholder.docNo=Please Enter Document Number
enforcement.infoRegist.placeholder.type=Please Enter Document Type
enforcement.infoRegist.placeholder.licenseNumber=Please Enter License Number
enforcement.infoRegist.placeholder.licenseType=Please Enter License Type
enforcement.infoRegist.placeholder.name=Please Enter Name
enforcement.infoRegist.placeholder.phone=Please Enter Phone
enforcement.infoRegist.placeholder.email=Please Enter Email
enforcement.infoRegist.placeholder.vehiclType=Please Enter Vehicle Type
enforcement.infoRegist.placeholder.vehiclePlateNo=Please Enter Vehicle Plate No.
enforcement.infoRegist.placeholder.address=Please Enter Address
enforcement.infoRegist.placeholder.penalty=Please Enter Penalty
enforcement.infoRegist.placeholder.officer=Please Enter Officer
enforcement.infoRegist.placeholder.location=Please Enter Location
enforcement.infoRegist.placeholder.detail=Please Enter Detail
enforcement.infoRegist.msg.date.invalid=Please enter a date in the past. Future dates are not allowed.
enforcement.infoRegist.msg.check.register=Would you like to register a traffic enforcement? The violator will be notified immediately upon registration.
enforcement.infoRegist.title.check.register=Check traffic enforcement information

#infoModify.html
enforcement.infoModify.title=Traffic enforcement modifications
enforcement.infoModify.enforcementNumber=Enforcement No.
enforcement.infoModify.violationNumber=Violation No.
enforcement.infoModify.placeOfViolate=Location
enforcement.infoModify.intermittentName=Violation
enforcement.infoModify.fine=Penalty
enforcement.infoModify.violationDate=Date
enforcement.infoModify.violatorsName=Name
enforcement.infoModify.cancellation=Cancel
enforcement.infoModify.save=Save
enforcement.infoModify.tfcEnfDetail=Details
enforcement.infoModify.lng=Longitude
enforcement.infoModify.lat=Latitude
enforcement.infoModify.msg.date.invalid=Please enter a date in the past. Future dates are not allowed.

#log common
enforcement.log.common.reqId=Requested ID
enforcement.log.common.successOrNot=Status
enforcement.log.common.logSuccess=Success
enforcement.log.common.logFail=Failure
enforcement.log.common.requestor=Requested by
enforcement.log.common.reqIp=IP
enforcement.log.common.reqDetail=Details
enforcement.log.common.creationDate=Date

#logList.html
enforcement.log.list.title=Total Logs
enforcement.log.list.descr=Manage history of logs
enforcement.log.list.comment=Comments
enforcement.log.list.registerType=Register Type
enforcement.log.list.check=Search
enforcement.log.list.tableNumber=No.
enforcement.log.list.enforcementInformationCode=Enforcement Code

#logDetail.html
enforcement.log.detail.title=Log Details

#detectionCommon
enforcement.detection.common.signalSystem = Signal System
enforcement.detection.common.signalInfo = Signal Info
enforcement.detection.common.signalInfo.0 = Red signal
enforcement.detection.common.signalInfo.1 = Yellow signal
enforcement.detection.common.signalInfo.2 = Left turn signal
enforcement.detection.common.signalInfo.3 = Green signal
enforcement.detection.common.enforceMode = TrafficEnforcement Mode
enforcement.detection.common.enforceMode.0 = Speed
enforcement.detection.common.enforceMode.1 = Bus
enforcement.detection.common.enforceMode.2 = Signal
enforcement.detection.common.enforceCode = TrafficEnforcement Code
enforcement.detection.common.enforceCode.0 = Speeding
enforcement.detection.common.enforceCode.1 = Bus
enforcement.detection.common.enforceCode.2 = Signal violation

#detectionList.html
enforcement.detectionList.title=Violation List
enforcement.detectionList.subTitle=Displays a list of violators caught by traffic enforcement equipment
enforcement.detectionList.eqpNm = Equipment Name
enforcement.detectionList.roadAddr = Road Address
enforcement.detectionList.eqpTime = Equipment Time
enforcement.detectionList.carPlate = Vehicle Plate No.
enforcement.detectionList.eqpYn = TrafficEnforcement Status
enforcement.detectionList.eqpYnY = Registration completed
enforcement.detectionList.eqpYnN = Waiting for registration

#detectionDetail.html
enforcement.detectionDetail.title=Violation Details
enforcement.detectionDetail.eqpNm=Equipment Name
enforcement.detectionDetail.roadAddr=Road Address
enforcement.detectionDetail.eqpTime = Equipment Time
enforcement.detectionDetail.carPlate = Vehicle Plate No.
enforcement.detectionDetail.eqpYn = TrafficEnforcement Status
enforcement.detectionDetail.eqpYnY = Registration completed
enforcement.detectionDetail.eqpYnN = Waiting for registration
enforcement.detectionDetail.avgSpeed=Average speed
enforcement.detectionDetail.enforceSpeed=Traffic enforcement speed
enforcement.detectionDetail.lmtSpeed=Speed limit
enforcement.detectionDetail.enforceLane=TrafficEnforcement lane
enforcement.detectionDetail.enforceImageList=TrafficEnforcement Image List
enforcement.detectionDetail.enforceImage=TrafficEnforcement Image
enforcement.detectionDetail.image.empty=There is no registered picture.
enforcement.detectionDetail.eqpNm.null=No Matching Equipment
enforcement.detectionDetail.deleted=Deleted
enforcement.detectionDetail.btn.detail=View details
enforcement.detectionDetail.equipmentId = Equipment ID
enforcement.detectionDetail.btn.modify=Modify
enforcement.detectionDetail.btn.approval=Approval

#detectionRegist.html
enforcement.detectionRegist.title=Traffic Equipment Enforcement Register
enforcement.detectionRegist.placeOfViolate=Location
enforcement.detectionRegist.fine=Penalty
enforcement.detectionRegist.violationDate=Date
enforcement.detectionRegist.violatorsName=Name
enforcement.detectionRegist.addr=Address
enforcement.detectionRegist.list=List
enforcement.detectionRegist.tfcEnfDetail=Details
enforcement.detectionRegist.lng=Longitude
enforcement.detectionRegist.lat=Latitude
enforcement.detectionRegist.licenseNumber= License Number
enforcement.detectionRegist.licenseTy=License Type
enforcement.detectionRegist.docType=Document Type
enforcement.detectionRegist.docNo=Document Nid
enforcement.detectionRegist.birthday=Birthday
enforcement.detectionRegist.phone=Phone
enforcement.detectionRegist.email=Email
enforcement.detectionRegist.enfInfo=Enforcement Title
enforcement.detectionRegist.vehiclType=VehicleType
enforcement.detectionRegist.vehiclNo=Vehicle Plate No.
enforcement.detectionRegist.law=Illegal Law
enforcement.detectionRegist.lawChoose=Illegal Law Choose
enforcement.detectionRegist.lawDetail=Illegal Law Detail
enforcement.detectionRegist.lmtSpd=Limit Speed
enforcement.detectionRegist.vioSpd=Violation Speed
enforcement.detectionRegist.ovrSpd=Excess Speed
enforcement.detectionRegist.lane=Lane
enforcement.detectionRegist.polInCharge=Officer
enforcement.detectionRegist.polStationInCaharge=Police Station
enforcement.detectionRegist.placePayment=Place payment
enforcement.detectionRegist.enforceImageList=TrafficEnforcement Image List
enforcement.detectionRegist.enforceImage=TrafficEnforcement Image
enforcement.detectionRegist.div.province = Province
enforcement.detectionRegist.div.district = District
enforcement.detectionRegist.placeholder.enfInfo=Please Enter Enforcement Title
enforcement.detectionRegist.placeholder.docType=Please Enter Document Type
enforcement.detectionRegist.placeholder.docNo=Please Enter Document No
enforcement.detectionRegist.placeholder.dvrLcenNo=Please Enter Driver License Number
enforcement.detectionRegist.placeholder.vioNm = Please Enter Name
enforcement.detectionRegist.placeholder.vioPno = Please Enter Phone Number
enforcement.detectionRegist.placeholder.vioEmail = Please Enter Email
enforcement.detectionRegist.placeholder.vhRegNo = Please Enter Vehicle Plate Number
enforcement.detectionRegist.placeholder.addr = Please Enter Address
enforcement.detectionRegist.placeholder.totalPrice = Please Enter Penalty
enforcement.detectionRegist.placeholder.polNm = Please Enter Officer
enforcement.detectionRegist.placeholder.roadAddr = Please Enter Violation Road Address
enforcement.detectionRegist.placeholder.tfcEnfDetail = Please Enter Details
enforcement.detectionRegist.placeholder.lat = Please Enter Latitude
enforcement.detectionRegist.placeholder.lng = Please Enter Longitude
enforcement.detectionRegist.msg.date.invalid=Please enter a date in the past. Future dates are not allowed.