#common
accident.common.search.searchOp=Type
accident.common.search.selectAll=All
accident.common.search.serchTerm=Search
accident.common.search.placeholder=Please enter keyword
accident.common.search.dateOp=Date
accident.common.search.reset=Reset Search
accident.common.search.registBtn=Regist
accident.common.search.searchType.requestedId=Requested Id
accident.common.search.searchType.requestedBy=Requested by
accident.common.button.delete=Delete
accident.common.button.list=List
accident.common.button.register=Register
accident.common.button.modify=Modify
accident.common.button.tfcAcdntRegist=New Traffic Accident
accident.common.msg.date.invalid=Please enter a date in the past. Future dates are not allowed.
accident.common.document.no=Document No
accident.common.document.type=Document Type
accident.common.loading = Loading...

#searchdriver.html
accident.driver.search.title=Driver Search
accident.driver.search.descr=You can search by driver's license number.
accident.driver.search.searchOp=Filter
accident.driver.search.tableNo=No.
accident.driver.search.placeholder=Please enter keyword
accident.driver.search.name=Name
accident.driver.search.phNum=Contact
accident.driver.search.searchAddress=Address
accident.driver.search.licenseCheck=License Status
accident.driver.search.lcnCkAvailable=Valid
accident.driver.search.lcnCkStop=Suspended
accident.driver.search.lcnCkCancellation=Invalid
accident.driver.search.docType=Document Type
accident.driver.search.docNo=Document Number
accident.driver.search.sex=Sex
accident.driver.search.nid=NID
accident.driver.search.searchTitle=Driver Information
accident.driver.search.check=Search
accident.driver.search.reset=Reset Search
accident.driver.search.content=No Search Result
accident.driver.search.closeButton=Close
accident.driver.search.address=Address
accident.driver.search.email=E-Mail
accident.driver.search.driverLicense=License No.
accident.driver.search.driverType=License Type.
accident.driver.search.expiration=License Expiration Date.
accident.driver.search.birth=Birthday
accident.driver.search.vehicleNo=Vehicle No
accident.driver.search.vehicleType=Vehicle Type

#SearchDriverDetail.html
accident.driver.search.Detail.title=Driver Information
accident.driver.search.Detail.subtitle=Driver Detailed Information
accident.driver.search.Detail.name=Name
accident.driver.search.Detail.email=Email Address
accident.driver.search.Detail.nid=NID
accident.driver.search.Detail.docType=Document Type
accident.driver.search.Detail.docNo=Document Number
accident.driver.search.Detail.sex=Sex
accident.driver.search.Detail.driverLicense=License No.
accident.driver.search.Detail.LicenseCheck=License Status
accident.driver.search.Detail.expiration=License Expiration Date
accident.driver.search.Detail.driverRestrictions=Driver restrictions
accident.driver.search.Detail.vehicleRestrictions=Vehicle restrictions
accident.driver.search.Detail.drivetLicenseDate=Issued Date
accident.driver.search.Detail.licenseRenewal=Renewal Count
accident.driver.search.Detail.phoneNum=Contact
accident.driver.search.Detail.nationality=Nationality
accident.driver.search.Detail.address=Address
accident.driver.search.Detail.driverType=License Type.
accident.driver.search.Detail.birth=BirthDay
accident.driver.search.Detail.vehicleNo=Vehicle No
accident.driver.search.Detail.vehicleType=Vehicle Type
accident.driver.search.Detail.tfcAcdntId=Accident Id
accident.driver.search.Detail.vioNm=Name
accident.driver.search.Detail.roadAddr=Accident Road Address
accident.driver.search.Detail.dvrLcenId=DriverLicenseId
accident.driver.search.Detail.tfcAcdntDt=Accident Date
accident.driver.search.Detail.found=Found
accident.driver.search.Detail.result=results
accident.driver.search.Detail.resultNone=Not Found TrafficAccident Info
accident.driver.search.Detail.accidentHist=Traffic Accident history
accident.driver.search.Detail.accidentHist.desc= This is a list of previous traffic Accident records.

#searchCar.html
accident.car.search.title=Vehicle Search
accident.car.search.descr=You can search by vehicle plate number.
accident.car.search.carNum=Vehicle No.
accident.car.search.check=Search
accident.car.search.vehicleNo=Vehicle No
accident.car.search.name=Name
accident.car.search.phNum=Contact
accident.car.search.searchAddress=Address
accident.car.search.birth=Birthday
accident.car.search.docType=Document Type
accident.car.search.docNo=Document Number
accident.car.search.state=State
accident.car.search.area=Area

#SearchCarDetail.html
accident.car.search.Detail.title=Vehicle Information
accident.car.search.Detail.subtitle=Driver Detailed Information
accident.car.search.Detail.name=Name
accident.car.search.Detail.phoneNum=Contact
accident.car.search.Detail.address=Address
accident.car.search.Detail.docType=Document Type
accident.car.search.Detail.docNo=Document Number
accident.car.search.Detail.state=State
accident.car.search.Detail.area=Area
accident.car.search.Detail.birth=BirthDay

#searchListAjax
searchListAjax.vehicle.desc = The result of the query by vehicle number or document number.
searchListAjax.driver.desc = The result of the query by driver's license number.
searchListAjax.table.number = No.
searchListAjax.table.birth = BirthDay
searchListAjax.table.docNo=Document Number
searchListAjax.table.vehicleNo=Vehicle No.

#mngList.html
accident.mngList.title=Total Traffic Accident
accident.mngList.descr=Traffic accident information can be inquired through traffic accident case number, name, officer, and period information.
accident.mngList.searchOp=Filter
accident.mngList.dateOp=Date
accident.mngList.serchTerm=Search
accident.mngList.selectAll=All
accident.mngList.receptionNo=Case No.
accident.mngList.involvedPerson=Name
accident.mngList.personInCharge=Officer
accident.mngList.check=Search
accident.mngList.tableNumber=No.
accident.mngList.accidentNumber=Case No.
accident.mngList.accidentType=Accident Type
accident.mngList.accidentDate=Date
accident.mngList.accidentPlace=Location
accident.mngList.registrationAccident=Register
accident.mngList.placeholder=Please enter keyword

#logList.html
accident.logList.title=Traffic Log
accident.logList.descr=Check the traffic accident log information.
accident.logList.searchOp=Filter
accident.logList.dateOp=Date
accident.logList.serchTerm=Search
accident.logList.selectAll=All
accident.logList.requestId=Log ID
accident.logList.requestor=Requested by
accident.logList.check=Search
accident.logList.trafficAccidentLogList=Traffic Accident Log List
accident.logList.tableNumber=No.
accident.logList.logDescr=Description
accident.logList.creationDate=Date
accident.logList.successOrFailure=Status
accident.logList.placeholder=Please enter keyword
accident.logList.registerType=Register Type

#accident.common
accident.common.target.title = Accident Party
accident.common.target.type.label = Target
accident.common.target.type.vehicle = Vehicle
accident.common.target.type.person = Person
accident.common.target.docType = Document Type
accident.common.target.docType.placeholder = Please enter Document Type
accident.common.target.docNo = Document No
accident.common.target.docNo.placeholder = Please enter Document No
accident.common.target.license.id = License Number
accident.common.target.license.id.placeholder.placeholder = Please enter License Number
accident.common.target.license.type = License Type
accident.common.target.vehicle.no = Vehicle Plate No.
accident.common.target.vehicle.no.placeholder = Please enter Vehicle Plate No.
accident.common.target.vehicle.type = Vehicle Type
accident.common.target.damage = Damage
accident.common.target.contact = Phone
accident.common.target.contact.placeholder = Please enter Phone number
accident.common.target.birth = Birthday
accident.common.target.name = Name
accident.common.target.name.placeholder = Please enter Name
accident.common.target.death.label = Deceased Status
accident.common.target.death.y = Deceased
accident.common.target.death.n = Not deceased
accident.common.target.vehicle.status = Vehicle Status
accident.common.target.vehicle.status.moving = Moving
accident.common.target.vehicle.status.stopped = Stopped
accident.common.target.btn.delete = Delete
accident.common.target.btn.add.passenger = Add Passenger

accident.common.passenger.title = Passenger
accident.common.passenger.driver.status.label = Driver?
accident.common.passenger.driver.status.y = Yes
accident.common.passenger.driver.status.n = No
accident.common.passenger.name.label = Name
accident.common.passenger.name.placeholder = Please Enter Name
accident.common.passenger.birth.label = Birth
accident.common.passenger.contact.label = Phone
accident.common.passenger.contact.placeholder = Please Enter Phone number
accident.common.passenger.address.label = Address
accident.common.passenger.address.placeholder = Please Enter Address
accident.common.passenger.email.label = Email
accident.common.passenger.email.placeholder = Please Enter Email
accident.common.passenger.damage.label = Damage
accident.common.passenger.damage.desc.label = Damage Description
accident.common.passenger.damage.desc.placeholder = Please Enter Damage Description
accident.common.passenger.death.label = Deceased Status
accident.common.passenger.death.y = Deceased
accident.common.passenger.death.n = Not deceased
accident.common.passenger.relationship = Relationship with driver
accident.common.passenger.license.id.label = License Number
accident.common.passenger.license.id.placeholder = Please Enter License Number
accident.common.passenger.license.type.label = License Type

#logDetail.html
accident.logDetail.title=Log Details

#mngRegist.html
accident.mngRegist.title=Traffic Accident Registration
accident.mngRegist.accidentNumber=Case No.
accident.mngRegist.officer=Please Enter Officer
accident.mngRegist.deptPlaceholer=It will be entered automatically
accident.mngRegist.typeOfAccident=Type
accident.mngRegist.accidentDate=Date
accident.mngRegist.accidentPlace=Location
accident.mngRegist.accidentPlaceholder=Please Enter Location
accident.mngRegist.policeOfficerInCharge=Officer in Charge
accident.mngRegist.list=List
accident.mngRegist.registrationButton=Register
accident.mngRegist.attachment=Attachment
accident.mngRegist.addaccidentParty=Add Accident Party
accident.mngRegist.report=Accident Report
accident.mngRegist.reportPlaceholder=Please Enter Accident Report
accident.mngRegist.childAcdnt=Child Accident
accident.mngRegist.childAcdnt.y=Yes
accident.mngRegist.childAcdnt.n=No
accident.mngRegist.accidentDetails=Details
accident.mngRegist.accidentDetailsPlaceholder=Please Enter Details
accident.mngRegist.lat=Latitude
accident.mngRegist.lng=Longitude

#AcdntmngDetail.html
accident.mngDetail.modifyButton=Modify
accident.mngDetail.accidentTypeDetails=Accident type details
accident.mngDetail.department=Department
accident.mngDetail.attachment=Attachment
accident.mngDetail.report=Accident Report

#AcdntmngModify.html
accident.mngModify.title=Traffic Accident Information Modification
accident.mngModify.cancelButton=Cancel
accident.mngModify.modifyFinish=Finish
accident.mngModify.accidentTypeDetails=Accident type details
accident.mngModify.department=Department
accident.mngModify.attachment=Attachment
