#common
accident.common.search.searchOp=Tipo
accident.common.search.selectAll=Tudo
accident.common.search.serchTerm=Pesquisar
accident.common.search.placeholder=Por favor, insira a palavra-chave
accident.common.search.dateOp=Data
accident.common.search.reset=Pesquisar Reset
accident.common.search.registBtn=Registrar
accident.common.search.searchType.requestedId=ID Solicitado
accident.common.search.searchType.requestedBy=Solicitado por
accident.common.button.delete=Excluir
accident.common.button.list=Lista
accident.common.button.register=Registrar
accident.common.button.modify=Modificar
accident.common.button.tfcAcdntRegist=Novo Acidente de Trânsito
accident.common.msg.date.invalid=Por favor, insira uma data no passado. Datas futuras não são permitidas.
accident.common.document.no=N º do documento
accident.common.document.type=Tipo de documento
accident.common.loading = Carregando...

#searchdriver.html
accident.driver.search.title=Pesquisa de motorista
accident.driver.search.descr=Você pode pesquisar pelo número da carteira de motorista.
accident.driver.search.searchOp=Filtro
accident.driver.search.tableNo=Nº
accident.driver.search.placeholder=Por favor, insira a palavra-chave
accident.driver.search.name=Nome
accident.driver.search.phNum=Contato
accident.driver.search.searchAddress=Endereço
accident.driver.search.licenseCheck=Status da Licença
accident.driver.search.lcnCkAvailable=Válida
accident.driver.search.lcnCkStop=Suspensa
accident.driver.search.lcnCkCancellation=Inválida
accident.driver.search.docType=Tipo de Documento
accident.driver.search.docNo=Número do Documento
accident.driver.search.sex=Sexo
accident.driver.search.nid=NID
accident.driver.search.searchTitle=Informações do Motorista
accident.driver.search.check=Pesquisar
accident.driver.search.reset=Redefinir Pesquisa
accident.driver.search.content=Nenhum Resultado Encontrado
accident.driver.search.closeButton=Fechar
accident.driver.search.address=Endereço
accident.driver.search.email=E-Mail
accident.driver.search.driverLicense=Nº da Licença
accident.driver.search.driverType=Tipo de Licença
accident.driver.search.expiration=Data de Validade da Licença
accident.driver.search.birth=Data de Nascimento
accident.driver.search.vehicleNo=Nº do Veículo
accident.driver.search.vehicleType=Tipo de Veículo

#SearchDriverDetail.html
accident.driver.search.Detail.title=Informações do Motorista
accident.driver.search.Detail.subtitle=Informações Detalhadas do Motorista
accident.driver.search.Detail.name=Nome
accident.driver.search.Detail.email=Endereço de Email
accident.driver.search.Detail.nid=NID
accident.driver.search.Detail.docType=Tipo de Documento
accident.driver.search.Detail.docNo=Número do Documento
accident.driver.search.Detail.sex=Sexo
accident.driver.search.Detail.driverLicense=Nº da Licença
accident.driver.search.Detail.LicenseCheck=Status da Licença
accident.driver.search.Detail.expiration=Data de Validade da Licença
accident.driver.search.Detail.driverRestrictions=Restrições do Motorista
accident.driver.search.Detail.vehicleRestrictions=Restrições do Veículo
accident.driver.search.Detail.drivetLicenseDate=Data de Emissão
accident.driver.search.Detail.licenseRenewal=Contagem de Renovações
accident.driver.search.Detail.phoneNum=Contato
accident.driver.search.Detail.nationality=Nacionalidade
accident.driver.search.Detail.address=Endereço
accident.driver.search.Detail.driverType=Tipo de Licença
accident.driver.search.Detail.birth=Data de Nascimento
accident.driver.search.Detail.vehicleNo=Nº do Veículo
accident.driver.search.Detail.vehicleType=Tipo de Veículo
accident.driver.search.Detail.tfcAcdntId=ID do Acidente
accident.driver.search.Detail.vioNm=Nome
accident.driver.search.Detail.roadAddr=Endereço da Via do Acidente
accident.driver.search.Detail.dvrLcenId=ID da Carteira de Motorista
accident.driver.search.Detail.tfcAcdntDt=Data do Acidente
accident.driver.search.Detail.found=Encontrado
accident.driver.search.Detail.result=resultados
accident.driver.search.Detail.resultNone=Informações de Acidente de Trânsito Não Encontradas
accident.driver.search.Detail.accidentHist=Histórico de Acidentes de Trânsito
accident.driver.search.Detail.accidentHist.desc=Esta é uma lista de registros de acidentes de trânsito anteriores.

#searchCar.html
accident.car.search.title=Pesquisa de veículos
accident.car.search.descr=Você pode pesquisar pelo número da placa do veículo.
accident.car.search.carNum=Nº do Veículo
accident.car.search.check=Pesquisar
accident.car.search.vehicleNo=Nº do Veículo
accident.car.search.name=Nome
accident.car.search.phNum=Contato
accident.car.search.searchAddress=Endereço
accident.car.search.birth=Aniversário
accident.car.search.docType=tipo de documento
accident.car.search.docNo=número do documento
accident.car.search.state=principal
accident.car.search.area=área

#searchCarDetail.html
accident.car.search.Detail.title=Informações do veículo
accident.car.search.Detail.subtitle=Informações Detalhadas do Condutor
accident.car.search.Detail.name=Nome
accident.car.search.Detail.phoneNum=Contato
accident.car.search.Detail.address=Endereço
accident.car.search.Detail.docType=tipo de documento
accident.car.search.Detail.docNo=número do documento
accident.car.search.Detail.state=principal
accident.car.search.Detail.area=área
accident.car.search.Detail.birth=Aniversário

#searchListAjax
searchListAjax.vehicle.desc = Resultado da consulta pelo número do veículo ou número do documento.
searchListAjax.driver.desc = Resultado da consulta pelo número da carteira de motorista.
searchListAjax.table.number = Nº
searchListAjax.table.birth = Data de Nascimento
searchListAjax.table.docNo = Número do Documento
searchListAjax.table.vehicleNo = Nº do Veículo

#mngList.html
accident.mngList.title=Total de Acidentes de Trânsito
accident.mngList.descr=Informações sobre acidentes de trânsito podem ser consultadas pelo número do caso, nome, oficial e período.
accident.mngList.searchOp=Filtro
accident.mngList.dateOp=Data
accident.mngList.serchTerm=Pesquisar
accident.mngList.selectAll=Tudo
accident.mngList.receptionNo=Número do Caso
accident.mngList.involvedPerson=Nome
accident.mngList.personInCharge=Oficial
accident.mngList.check=Pesquisar
accident.mngList.tableNumber=Nº
accident.mngList.accidentNumber=Número do Caso
accident.mngList.accidentType=Tipo de Acidente
accident.mngList.accidentDate=Data
accident.mngList.accidentPlace=Local
accident.mngList.registrationAccident=Registrar
accident.mngList.placeholder=Por favor, insira a palavra-chave

#logList.html
accident.logList.title=Registro de Tráfego
accident.logList.descr=Verifique as informações do registro de acidentes de trânsito.
accident.logList.searchOp=Filtro
accident.logList.dateOp=Data
accident.logList.serchTerm=Pesquisar
accident.logList.selectAll=Tudo
accident.logList.requestId=ID do Log
accident.logList.requestor=Solicitado por
accident.logList.check=Pesquisar
accident.logList.trafficAccidentLogList=Lista de Registros de Acidentes de Trânsito
accident.logList.tableNumber=Nº
accident.logList.logDescr=Descrição
accident.logList.creationDate=Data
accident.logList.successOrFailure=Status
accident.logList.placeholder=Por favor, insira a palavra-chave
accident.logList.registerType=Tipo de Registro

#accident.common
accident.common.target.title = Parte do Acidente
accident.common.target.type.label = Alvo
accident.common.target.type.vehicle = Veículo
accident.common.target.type.person = Pessoa
accident.common.target.docType = Tipo de Documento
accident.common.target.docType.placeholder = Por favor, insira o Tipo de Documento
accident.common.target.docNo = Número do Documento
accident.common.target.docNo.placeholder = Por favor, insira o Número do Documento
accident.common.target.license.id = Número da Carteira de Motorista
accident.common.target.license.id.placeholder = Por favor, insira o Número da Carteira de Motorista
accident.common.target.license.type = Tipo de Carteira de Motorista
accident.common.target.vehicle.no = Número da Placa do Veículo
accident.common.target.vehicle.no.placeholder = Por favor, insira o Número da Placa do Veículo
accident.common.target.vehicle.type = Tipo de Veículo
accident.common.target.damage = Dano
accident.common.target.contact = Telefone
accident.common.target.contact.placeholder = Por favor, insira o número de telefone
accident.common.target.birth = Data de Nascimento
accident.common.target.name = Nome
accident.common.target.name.placeholder = Por favor, insira o Nome
accident.common.target.death.label = Status de Falecimento
accident.common.target.death.y = Falecido
accident.common.target.death.n = Não falecido
accident.common.target.vehicle.status = Status do Veículo
accident.common.target.vehicle.status.moving = Em movimento
accident.common.target.vehicle.status.stopped = Parado
accident.common.target.btn.delete = Excluir
accident.common.target.btn.add.passenger = Adicionar Passageiro

accident.common.passenger.title = Passageiro
accident.common.passenger.driver.status.label = Motorista?
accident.common.passenger.driver.status.y = Sim
accident.common.passenger.driver.status.n = Não
accident.common.passenger.name.label = Nome
accident.common.passenger.name.placeholder = Por favor, insira o Nome
accident.common.passenger.birth.label = Data de Nascimento
accident.common.passenger.contact.label = Telefone
accident.common.passenger.contact.placeholder = Por favor, insira o número de telefone
accident.common.passenger.address.label = Endereço
accident.common.passenger.address.placeholder = Por favor, insira o Endereço
accident.common.passenger.email.label = E-mail
accident.common.passenger.email.placeholder = Por favor, insira o E-mail
accident.common.passenger.damage.label = Dano
accident.common.passenger.damage.desc.label = Descrição do Dano
accident.common.passenger.damage.desc.placeholder = Por favor, insira a Descrição do Dano
accident.common.passenger.death.label = Status de Falecimento
accident.common.passenger.death.y = Falecido
accident.common.passenger.death.n = Não falecido
accident.common.passenger.relationship = Relação com o motorista
accident.common.passenger.license.id.label = Número da Carteira de Motorista
accident.common.passenger.license.id.placeholder = Por favor, insira o Número da Carteira de Motorista
accident.common.passenger.license.type.label = Tipo de Carteira de Motorista

#logDetail.html
accident.logDetail.title=Detalhes do Log

#mngRegist.html
accident.mngRegist.title=Registro de Acidente de Trânsito
accident.mngRegist.accidentNumber=Nº do Caso
accident.mngRegist.officer=Por favor, insira o oficial
accident.mngRegist.deptPlaceholer=Será inserido automaticamente
accident.mngRegist.typeOfAccident=Tipo de Acidente
accident.mngRegist.accidentDate=Data do Acidente
accident.mngRegist.accidentPlace=Local do Acidente
accident.mngRegist.accidentPlaceholder=Insira o Local do Acidente
accident.mngRegist.policeOfficerInCharge=Oficial Responsável
accident.mngRegist.list=Lista
accident.mngRegist.registrationButton=Registrar
accident.mngRegist.attachment=Anexo
accident.mngRegist.addaccidentParty=Adicionar Parte no Acidente
accident.mngRegist.report=Relatório de Acidente
accident.mngRegist.reportPlaceholder=Insira o Relatório de Acidente
accident.mngRegist.childAcdnt=Acidente Infantil
accident.mngRegist.childAcdnt.y=Sim
accident.mngRegist.childAcdnt.n=Não
accident.mngRegist.accidentDetails=Detalhes do Acidente
accident.mngRegist.accidentDetailsPlaceholder=Insira os Detalhes do Acidente
accident.mngRegist.lat=Latitude
accident.mngRegist.lng=Longitude

#AcdntmngDetail.html
accident.mngDetail.modifyButton=Modificar
accident.mngDetail.accidentTypeDetails=Detalhes do Tipo de Acidente
accident.mngDetail.department=Departamento
accident.mngDetail.attachment=Anexo
accident.mngDetail.report=Relatório de Acidente

#AcdntmngModify.html
accident.mngModify.title=Modificação das Informações do Acidente de Trânsito
accident.mngModify.cancelButton=Cancelar
accident.mngModify.modifyFinish=Concluir
accident.mngModify.accidentTypeDetails=Detalhes do Tipo de Acidente
accident.mngModify.department=Departamento
accident.mngModify.attachment=Anexo
