#common
administ.common.searchCon=Tipo
administ.common.selectAll=Todos
administ.common.check=Pesquisar
administ.common.searchOp=Opção de Pesquisa
administ.common.dateOp=Data
administ.common.enforcementNumber=Número de Execução
administ.common.serchTerm=Pesquisar
administ.common.placeholder=Por favor, insira a palavra-chave
administ.common.search.reset=Resetar Pesquisa
administ.common.caseType=Tipo de Caso
administ.common.civilCases=Civil
administ.common.criminalCases=Criminal
administ.common.transferDate=Data de Transferência
administ.common.administrativeDate=Data de transição de disposição administrativa
administ.common.retentionSttts=Retenção
administ.common.retentionY=Sim
administ.common.retentionN=Não
administ.common.handlingStts=Status
administ.common.handlingPrcss=Em andamento
administ.common.handlingCmplt=Concluído
administ.common.caseNumber=Número do Caso
administ.common.administNumber=Número de Administração de Tráfego
administ.common.driverName=Nome
administ.common.courtInCharge=Departamento
administ.common.driverAddress=Endereço
administ.common.driverPhone=Contato
administ.common.penalty=Quantia da Multa
administ.common.retentionAddress=Local de Transferência
administ.common.search.searchOp=Filtro
administ.common.search.selectAll=Todos
administ.common.search.dateOp=Data
administ.common.search.placeholder=Por favor, insira a palavra-chave

#AdministMngList.html
administ.mngList.title=Gestão de Transferências Judiciais
administ.mngList.descr=Gerenciar sujeitos de transferência judicial
administ.mngList.registrationCountTransfer=Registrar
administ.mngList.tableNumber=Nº

#AdministMngDetail
administ.mngDetail.caseDetail=Detalhes do Caso
administ.mngDetail.judgeResults=Decisão Judicial
administ.mngDetail.judgeInCharge=Juiz
administ.mngDetail.judgeFineInfo=Quantia da Multa
administ.mngDetail.judgeViolation=Violação
administ.mngDetail.judgeDetail=Detalhes
administ.mngDetail.listButton=Lista
administ.mngDetail.modifyButton=Modificar
administ.mngDetail.saveButton=Salvar


#lawList.html
administ.lawList.title=Leis de Tráfego Totais
administ.lawList.descr=Gerenciar informações sobre leis de tráfego
administ.lawList.check=Pesquisar
administ.lawList.tableNumber=Nº
administ.lawList.articleId=Artigo ID
administ.lawList.constructer=Registrado por
administ.lawList.lawRegistration=Registrar
administ.lawList.dateOfRevision=Data da Revisão
administ.lawList.lawType = Tipo de Lei
administ.lawList.repealStatus = Status
administ.lawList.repealStatus.y = Revogado
administ.lawList.repealStatus.n = Não Revogado

#lawRegist.html
administ.lawRegist.title=Registrar Lei de Tráfego
administ.lawRegist.articleId=Artigo ID
administ.lawRegist.lawType=Tipo de Lei
administ.lawRegist.legalExplanation=Detalhes da Lei
administ.lawRegist.list=Lista
administ.lawRegist.registrationTitle=Registrar
administ.lawRegist.registrationButton=Registrar
administ.lawRegist.dateOfPromulgation=Data da Promulgação
administ.lawRegist.addFine=Adicionar Multa

administ.lawRegist.articelNo=Número do Artigo
administ.lawRegist.paragraph=Alínea
administ.lawRegist.additionalPenalty=Pena Acessória
administ.lawRegist.contraventionType=Tipo de Contravenção
administ.lawRegist.transgressionType=Tipo de Transgressão

#lawRegist.placeholder.html
administ.lawRegist.placeholder.legalNumber=Por favor, insira o número da lei
administ.lawRegist.placeholder.legalExplanation=Por favor, insira os detalhes do equipamento de fiscalização

#lawDetail.html
administ.lawDetail.title=Detalhes da Lei
administ.lawDetail.descr=Informações Detalhadas
administ.lawDetail.subtitle=Detalhes
administ.lawDetail.lawType=Tipo de Lei
administ.lawDetail.constructer=Registrado por
administ.lawDetail.legalExplanation=Detalhes
administ.lawDetail.articleId=Artigo ID
administ.lawDetail.creationDate=Data de Registro
administ.lawDetail.deleteButton=Revogar
administ.lawDetail.listButton=Lista
administ.lawDetail.modifyButton=Modificar
administ.lawDetail.removeButton=Remover
administ.lawDetail.modifyCfrmButton=Você gostaria de alterar a lei?
administ.lawDetail.deleteCfrmButton=Você gostaria de revogar a lei?
administ.lawDetail.addButton=Revisar
administ.lawDetail.addFine=Adicionar Multa
administ.lawDetail.cancel=Cancelar
administ.lawDetail.fineList=Lista de Multas
administ.lawDetail.lastUpdDt=Data da Última Atualização
administ.lawDetail.repealDe=Data de Abolição
administ.lawDetail.fineDescription=Descrição da Multa
administ.lawDetail.finePrice=Preço da Multa
administ.lawDetail.adtnRvsnDt=Data da Revisão Adicional
administ.lawDetail.adtnRvsnDetail=Detalhes da Revisão Adicional
administ.lawDetail.repealLaw=Esta é uma disposição legal revogada.
administ.lawDetail.lawRecovery=Recuperação Legal
administ.lawDetail.revisedContent=Conteúdo Revisado
administ.lawDetail.placeholder=Por favor, insira seu conteúdo

administ.lawDetail.articelNo=Número do Artigo
administ.lawDetail.paragraph=Alínea
administ.lawDetail.additionalPenalty=Pena Acessória
administ.lawDetail.contraventionType=Tipo de Contravenção
administ.lawDetail.transgressionType=Tipo de Transgressão

#lawModify.html
administ.lawModify.title=Modificar Informações da Lei
administ.lawModify.subtitle=Modificar
administ.lawModify.constructer=Registrado por
administ.lawModify.legalExplanation=Detalhes
administ.lawModify.lawType=Tipo de Lei
administ.lawModify.articleId=Artigo ID
administ.lawModify.creationDate=Data
administ.lawModify.cancelButton=Cancelar
administ.lawModify.fineList=Lista de Multas
administ.lawModify.modifyFinish=Modificar
administ.lawModify.adtnRvsnDt=Data da Revisão Adicional
administ.lawModify.adtnRvsnDetail=Detalhes da Revisão Adicional
administ.lawModify.lastUpdDt=Data da Última Atualização
administ.lawModify.fineDescription=Descrição da Multa
administ.lawModify.finePrice=Preço da Multa
administ.lawModify.saveButton=Salvar

administ.lawModify.articelNo=Número do Artigo
administ.lawModify.paragraph=Alínea
administ.lawModify.additionalPenalty=Pena Acessória
administ.lawModify.contraventionType=Tipo de Contravenção
administ.lawModify.transgressionType=Tipo de Transgressão
