#common
user.common.statusOk=Válido
user.common.statusStopped=Inválido
user.common.statusWaiting=Aguardando aprovação
user.common.statusWithdraw=Retirar
user.common.usageHistory=Histórico
user.common.usageTime=Tempo
user.common.jur=Jurisdição

#adminList.html
user.adminList.title=Administrador
user.adminList.subTitle=Você pode gerenciar Administradores.

#adminDetail.html
user.adminDetail.confirm.delete=Você deseja excluir as informações do seu membro?
user.adminDetail.confirm.modify=Você gostaria de editar as informações do seu membro?

#operatorList.html
user.operatorList.title=Operador
user.operatorList.subTitle=Você pode gerenciar Operadores

#polList.html
user.polList.title=Policial
user.polList.subTitle=Você pode gerenciar Policiais

#PolDetail.html
user.polDetail.title.detail=Detalhes do Policial

#polRegist.html
user.polRegist.title=Registro de Policial
user.polRegist.polLcenId=ID da Conta do Policial
user.polRegist.polLcenDate=Data de aquisição da licença policial
user.polRegist.password = Senha
user.polRegist.email = Email
user.polRegist.name = Nome
user.polRegist.tel = Contatos
user.polRegist.jur = Jurisdição
user.polRegist.policeStation = Estação de Polícia
user.polRegist.search = Buscar
user.polRegist.brth = Aniversário
user.polRegist.applyMembership = Inscrever-se

user.polRegist.placeholder.polLcenId=Por favor, insira o ID da conta do policial
user.polRegist.placeholder.name=Por favor, insira o nome
user.polRegist.placeholder.password=Por favor, insira a senha
user.polRegist.placeholder.enterTel = Por favor, insira o contato
user.polRegist.placeholder.enterEmail = Por favor, insira o email
user.polRegist.placeholder.enterPoliceStation = Por favor, insira a estação de polícia
user.polRegist.placeholder.id = Número da Licença do Policial

user.polRegist.validation.inputResult = Por favor, insira todos os dados
user.polRegist.validation.brthResult = Por favor, selecione a data de aquisição da licença
user.polRegist.validation.polLcenDtResult = Por favor, selecione sua data de nascimento