#common
user.common.statusOk=Valid
user.common.statusStopped=Invalid
user.common.statusWaiting=Waiting for approval
user.common.statusWithdraw=Withdraw
user.common.usageHistory=History
user.common.usageTime=Time
user.common.jur=Jurisdiction

#adminList.html
user.adminList.title=Admin
user.adminList.subTitle=You can manage Administrators.

#adminDetail.html
user.adminDetail.confirm.delete=Do you want to delete your member information?
user.adminDetail.confirm.modify=Would you like to edit your member information?

#operatorList.html
user.operatorList.title=Operator
user.operatorList.subTitle=You can manage Operator

#polList.html
user.polList.title=Police Officer
user.polList.subTitle=You can manage Police Officer

#PolDetail.html
user.polDetail.title.detail=Police Officer

#polRegist.html
user.polRegist.title=Police Officer Regist
user.polRegist.polLcenId=Police Officer Account Id
user.polRegist.polLcenDate=Police license acquisition date
user.polRegist.password = Password
user.polRegist.email = Email
user.polRegist.name = Name
user.polRegist.password = Password
user.polRegist.tel = Contacts
user.polRegist.email = Email
user.polRegist.jur = Jurisdiction
user.polRegist.policeStation = Police Station
user.polRegist.search = Search
user.polRegist.brth = Birthday
user.polRegist.polLcenDate = Police license acquisition date
user.polRegist.applyMembership = Join

user.polRegist.placeholder.polLcenId=Please Input Police Officer Acoount Id
user.polRegist.placeholder.name=Please enter name
user.polRegist.placeholder.password=Please enter password
user.polRegist.placeholder.enterTel = Please enter contact
user.polRegist.placeholder.enterEmail = Please enter Email
user.polRegist.placeholder.enterPoliceStation = Please enter Police Station
user.polRegist.placeholder.id = Police Officer License Number

user.polRegist.validation.inputResult = Please enter all inputs
user.polRegist.validation.brthResult = Please select the license acquisition date
user.polRegist.validation.polLcenDtResult = Please select your birthday 

